# =============================================================================
# Recursive bootstrap bounds tests for fqardl() and fnardl() (new in 1.1.0)
#
# The pseudo-samples are generated by the shared engine in ardl_boot_engine.R
# (copied verbatim from ardlverse). This file only supplies fqardl's own
# design: the statistics of every replication are computed by the same
# design builders that produce the reported model, and the Fourier frequency
# and the lag orders can be re-selected in every replication.
# =============================================================================

# OLS bounds statistics on a given conditional ECM design:
# Fov = Wald / m on the lagged levels (y and x), t on the lagged level of y,
# Find = Wald / m on the lagged levels of the regressors.
.fq_ols_stats <- function(Yv, Xd, ylev, xlev) {
  qx <- qr(Xd)
  if (qx$rank < ncol(Xd)) stop("rank-deficient design", call. = FALSE)
  b <- qr.coef(qx, Yv)
  e <- qr.resid(qx, Yv)
  df <- nrow(Xd) - ncol(Xd)
  s2 <- sum(e^2) / df
  piv <- order(qx$pivot)
  V <- s2 * chol2inv(qr.R(qx))[piv, piv, drop = FALSE]
  nm <- colnames(Xd)
  Fw <- function(cols) {
    i <- match(cols, nm)
    if (anyNA(i)) stop("level terms not found in the design", call. = FALSE)
    bi <- b[i]
    drop(crossprod(bi, solve(V[i, i, drop = FALSE], bi))) / length(i)
  }
  iy <- match(ylev, nm)
  c(Fov = Fw(c(ylev, xlev)), t = unname(b[iy] / sqrt(V[iy, iy])), Find = Fw(xlev))
}

# Fourier terms of a spec: the matrix itself or the frequency k
.fq_spec_fourier <- function(spec, n) {
  if (!is.null(spec$fourier)) spec$fourier else generate_fourier_terms(n, spec$k)
}

# Statistics of fqardl's ECM (build_ardl_design), estimated by OLS
.fq_stats_qardl <- function(y, X, spec) {
  X <- as.matrix(X)
  d <- build_ardl_design(y, X, .fq_spec_fourier(spec, length(y)), spec$p, spec$q)
  if (is.null(d)) stop("insufficient observations", call. = FALSE)
  .fq_ols_stats(d$y, d$X, "y_lag1", paste0("x", seq_len(ncol(X)), "_lag1"))
}

# Gaussian log-likelihood of an OLS fit as computed by stats::logLik.lm
.fq_loglik <- function(e) {
  N <- length(e)
  0.5 * (-N * (log(2 * pi) + 1 - log(N) + log(sum(e^2))))
}

.fq_ic <- function(ll, k, n, criterion) {
  switch(criterion,
         "AIC" = -2 * ll + 2 * k,
         "BIC" = -2 * ll + log(n) * k,
         "HQ"  = -2 * ll + 2 * log(log(n)) * k)
}

# Same choice as select_fourier_frequency(), computed with qr() instead of
# lm() for speed inside the bootstrap (equality is checked by a test).
.fq_select_k_fast <- function(y, X, max_k, criterion) {
  n <- length(y)
  ic <- numeric(max_k)
  for (k in 1:max_k) {
    Z <- cbind(1, X, generate_fourier_terms(n, k))
    ic[k] <- .fq_ic(.fq_loglik(qr.resid(qr(Z), y)), ncol(Z), n, criterion)
  }
  which.min(ic)
}

# Same choice as select_optimal_lags(), computed with qr() instead of lm()
.fq_select_lags_fast <- function(y, X, fourier, max_p, max_q, criterion) {
  n <- length(y)
  best_ic <- Inf
  bp <- 1
  bq <- 1
  for (p in 1:max_p) {
    for (q in 1:max_q) {
      if (n - max(p, q) < 20) next
      d <- build_ardl_design(y, X, fourier, p, q)
      if (is.null(d)) next
      ic <- .fq_ic(.fq_loglik(qr.resid(qr(d$X), d$y)), ncol(d$X), d$n, criterion)
      if (is.finite(ic) && ic < best_ic) {
        best_ic <- ic
        bp <- p
        bq <- q
      }
    }
  }
  list(optimal_p = bp, optimal_q = bq)
}

# Selection callback: re-runs fqardl's selection of the Fourier frequency
# (unless fixed in 'reselect$k') and of the lag orders on a bootstrap sample,
# with the criteria of select_fourier_frequency() and select_optimal_lags().
# 'transform' maps the simulated regressors to the regressors used in the
# selection (identity for fqardl, partial sums for fnardl).
.fq_make_select <- function(reselect, transform = function(x) as.matrix(x)) {
  if (is.null(reselect)) return(NULL)
  function(yy, xx) {
    Xs <- transform(xx)
    k <- if (is.null(reselect$k))
      .fq_select_k_fast(yy, Xs, reselect$max_k, reselect$criterion)
    else reselect$k
    fr <- generate_fourier_terms(length(yy), k)
    lg <- .fq_select_lags_fast(yy, Xs, fr, reselect$max_p, reselect$max_q,
                               reselect$criterion)
    list(k = k, fourier = fr, p = lg$optimal_p, q = lg$optimal_q)
  }
}

# Engine settings of the two schemes
.fq_scheme <- function(scheme) {
  if (scheme == "bvz")
    list(nulls = "separate", xmodel = "vecm", init = "block", recentre = "draw",
         label = "Bertelli, Vacca and Zoia (2022): separate null models for Fov, t and Find")
  else
    list(nulls = "joint", xmodel = "var", init = "observed", recentre = "once",
         label = paste("the Fov null for all statistics (McNown, Sam and Goh 2018, Steps 1-8)",
                       "applied to the conditional ECM (package choice)"))
}

# Common result layout of the two bootstrap functions
.fq_boot_result <- function(eng, scheme, n_boot, reselect, model) {
  sc <- .fq_scheme(scheme)
  list(
    method       = paste0("Recursive bootstrap bounds test (", sc$label,
                          "); OLS conditional ECM statistics"),
    model        = model,
    scheme       = scheme,
    n_boot       = n_boot,
    statistic    = eng$statistic,
    orig_F       = unname(eng$statistic["Fov"]),
    orig_t       = unname(eng$statistic["t"]),
    orig_Find    = unname(eng$statistic["Find"]),
    boot_F       = eng$boot[, "Fov"],
    boot_t       = eng$boot[, "t"],
    boot_Find    = eng$boot[, "Find"],
    p_value_F    = unname(eng$p_value["Fov"]),
    p_value_t    = unname(eng$p_value["t"]),
    p_value_Find = unname(eng$p_value["Find"]),
    p_value      = unname(eng$p_value["t"]),
    cv           = eng$cv,
    reject       = eng$reject,
    level        = eng$level,
    decision     = eng$decision,
    label        = eng$label,
    n_valid      = eng$n_valid,
    reselect     = !is.null(reselect),
    k_fixed      = !is.null(reselect) && !is.null(reselect$k),
    engine       = eng
  )
}

# Text block printed by summary() for a bootstrap result
.fq_print_boot <- function(b) {
  cat(sprintf("Scheme: %s, %d replications (valid: %s)\n", b$scheme, b$n_boot,
              paste(b$n_valid, collapse = "/")))
  cat(sprintf("Statistics (OLS conditional ECM): Fov = %.4f, t = %.4f, Find = %.4f\n",
              b$orig_F, b$orig_t, b$orig_Find))
  cat(sprintf("Bootstrap p-values: Fov = %.4f, t = %.4f, Find = %.4f\n",
              b$p_value_F, b$p_value_t, b$p_value_Find))
  cat(sprintf("Bootstrap critical values (%g%%): Fov = %.4f, t = %.4f, Find = %.4f\n",
              100 * b$level, b$engine$cv_level["Fov"], b$engine$cv_level["t"],
              b$engine$cv_level["Find"]))
  cat(sprintf("Decision (Fov AND t AND Find): %s\n", b$label))
  if (isTRUE(b$reselect))
    cat(if (isTRUE(b$k_fixed))
      "Fourier frequency fixed by the user; lag orders re-selected in every replication.\n"
      else "Fourier frequency and lag orders re-selected in every replication.\n")
  else
    cat("Fourier frequency and lag orders held fixed at the selected values.\n")
}
